name: Release Obsidian plugin

# Change "plugin.zip" to match the plugin ID from manifest.json.
env:
  PLUGIN_ZIP_NAME: plugin.zip

on:
    workflow_dispatch:
    push:
        tags:
            # Trigger when a new tag is pushed
            - "*"

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3

            -   name: Use Node.js
                uses: actions/setup-node@v3
                with:
                    node-version: "23.x"

            -   name: Build plugin
                run: |
                    npm install
                    npm run build

            -   name: Create zip archive
                run: |
                    cd dist
                    zip -r ../${{ env.PLUGIN_ZIP_NAME }} .

            -   name: Create release
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: |
                    tag="${GITHUB_REF#refs/tags/}"
                    
                    gh release create "$tag" \
                      --title="$tag" \
                      --draft \
                      ${{ env.PLUGIN_ZIP_NAME }} dist/main.js dist/styles.css dist/manifest.json
